### ISSUE TITLE
Blank page with firebase

### ISSUE THREAD

**Issue by pharyon** [SkyJedi/SWRPG-Web-Dice-Roller#13]
Hi,
I just follow all the #Installation and Setup.
The website on firebase just display the index page  SWRPG Web Dice Roller with no element, picture or script.
I tried on my local computer with "NPM start" and it was ok.
I do not know what i forgot.

**Comment by SkyJedi** [comment]
I'm betting something is missing or outdated in package.json.  Try running npm update then build and deploy the updated app.

**Comment by pharyon** [comment]
Thank you SkyJedi, the update help.... and deploy 'src'.
